#ifndef SEVSEGMENTS_CONFIG_H_
#define SEVSEGMENTS_CONFIG_H_

/*
*	Choose PortNo for SevSegment Common Pin 1,2,3
*/
#define SEVSEGMENTS1_COMMON_PIN_PORT	GPIO_PORTD
#define SEVSEGMENTS2_COMMON_PIN_PORT	GPIO_PORTD
#define SEVSEGMENTS3_COMMON_PIN_PORT	GPIO_PORTD

/*
*	Choose PinNumber for SevSegment 1,2,3
*/
#define SEVSEGMENTS1_COMMON_PIN			PIN_0
#define SEVSEGMENTS2_COMMON_PIN			PIN_1
#define SEVSEGMENTS3_COMMON_PIN			PIN_2

/*
*	Choose PortNo for SevSegment 1,2,3
*/
#define SEVSEGMENTS1_ATTACHED_PORT		GPIO_PORTA
#define SEVSEGMENTS2_ATTACHED_PORT		GPIO_PORTB
#define SEVSEGMENTS3_ATTACHED_PORT		GPIO_PORTC


#endif /* SEVSEGMENTS_CONFIG_H_ */