#ifndef SEVSEGMENTS_CONFIG_H_
#define SEVSEGMENTS_CONFIG_H_

/*
*	Choose PortNo for SevSegment Common Pin 1,2,3
*/
#define SEVSEGMENTS1_COMMON_PIN_PORT	GPIO_PORT_D
#define SEVSEGMENTS2_COMMON_PIN_PORT	GPIO_PORT_D
#define SEVSEGMENTS3_COMMON_PIN_PORT	GPIO_PORT_D

/*
*	Choose PinNumber for SevSegment 1,2,3
*/
#define SEVSEGMENTS1_COMMON_PIN			GPIO_PIN_D0
#define SEVSEGMENTS2_COMMON_PIN			GPIO_PIN_D1
#define SEVSEGMENTS3_COMMON_PIN			GPIO_PIN_D2

/*
*	Choose PortNo for SevSegment 1,2,3
*/
#define SEVSEGMENTS1_ATTACHED_PORT		GPIO_PORT_A
#define SEVSEGMENTS2_ATTACHED_PORT		GPIO_PORT_B
#define SEVSEGMENTS3_ATTACHED_PORT		GPIO_PORT_C


#endif /* SEVSEGMENTS_CONFIG_H_ */